MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: ResNet.add_ResNet50_conv4_body
  NUM_CLASSES: 81
  FASTER_RCNN: True
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.01
  GAMMA: 0.1
  # 2x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 360000
  STEPS: [0, 240000, 320000]
RPN:
  SIZES: (32, 64, 128, 256, 512)
FAST_RCNN:
  ROI_BOX_HEAD: ResNet.add_ResNet_roi_conv5_head
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  DATASETS: ('coco_2014_train', 'coco_2014_valminusminival')
  SCALES: (800,)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
TEST:
  DATASETS: ('coco_2014_minival',)
  SCALES: (800,)
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: .
